### ISSUE TITLE
References

### ISSUE THREAD

**Issue by mezantrop** [timcera/toolbox_utils#2]
https://github.com/timcera/toolbox_utils/blob/5dcf22e8022008c6c03b27d2955c627388bc400d/src/toolbox_utils/tsutils.py#L80

Would be nice if you make references to original projects :)

**Comment by timcera** [comment]
I apologize.  In order to make toolbox_utils a conda package on conda-forge I need all dependencies available to conda.  That is why I incorporated tssplit directly into toolbox_utils, but you are correct - I should have acknowledged the source.

Just pushed a commit that includes the entire tssplit project as a git submodule.  So now the tssplit license, readme, ...etc are all now visible to any toolbox_utils user.

**Comment by mezantrop** [comment]
Appreciated a lot. Have a nice weekend :)
